/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_gumbo.vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import projeto_gumbo.Produto;
import projeto_gumbo.GestaoGumbo;
import projeto_gumbo.Stock;
import projeto_gumbo.TipoMovimento;
import projeto_gumbo.TipoProduto;
import projeto_gumbo.TipoPreco;

/**
 *
 * @author dicasado
 */
public class Gumbo extends javax.swing.JFrame {

    private DefaultListModel modeloListaProdutos;
    private DefaultListModel demoList = new DefaultListModel();
    private int fieldLength = 0;

    /**
     * Creates new form GestaoGumbo
     */
    public Gumbo() {
        initComponents();
        GestaoGumbo gestor = GestaoGumbo.getGumbo();

        actualizarListaProd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProdutos = new javax.swing.JList();
        btnAdicionar = new javax.swing.JToggleButton();
        btnConsultar = new javax.swing.JToggleButton();
        searchTxt = new javax.swing.JTextField();
        btnEditar = new javax.swing.JToggleButton();
        btnRemover = new javax.swing.JToggleButton();
        btnEntradaStock = new javax.swing.JToggleButton();
        btnSaidaStock = new javax.swing.JToggleButton();
        btnQuebraStock = new javax.swing.JToggleButton();
        btnSair = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gumbo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Gestão de Stock");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel2.setText("GUMBO");

        ListaProdutos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListaProdutos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaProdutos);

        btnAdicionar.setText("Adicionar Produtos");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar Produto");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });

        btnEditar.setText("Editar Produto");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover Produto");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnEntradaStock.setText("Entrada Stock");
        btnEntradaStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaStockActionPerformed(evt);
            }
        });

        btnSaidaStock.setText("Saida Stock");
        btnSaidaStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaStockActionPerformed(evt);
            }
        });

        btnQuebraStock.setText("Quebra Stock");
        btnQuebraStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuebraStockActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel3.setText("Procurar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEntradaStock, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuebraStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaidaStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemover)
                        .addGap(26, 26, 26)
                        .addComponent(btnEntradaStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaidaStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuebraStock)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        Produto p = new Produto(TipoProduto.Fruta, TipoPreco.KG, "", "", 0, 0);
        DadosProduto dialog = new DadosProduto(this, p);
        dialog.setVisible(true);

        if (dialog.isAceitado()) {
            GestaoGumbo.getGumbo().adicionarProd(p);
            actualizarListaProd();
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnQuebraStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuebraStockActionPerformed
        try {
            Produto p = (Produto) ListaProdutos.getSelectedValue();
            if (p.getQuantidade() == 0) {
                JOptionPane.showMessageDialog(null, "O produto selecionado não tem stock");
            } else {
                if (JOptionPane.showConfirmDialog(this, "Tem a certeza que quer tirar todo o stock de\n" + p.toString() + "?") == JOptionPane.YES_OPTION) {
                    p.setQuantidade(0);
                }
                actualizarListaProd();
            }
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }
    }//GEN-LAST:event_btnQuebraStockActionPerformed

    private void btnEntradaStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaStockActionPerformed
        try {
            Produto p = (Produto) ListaProdutos.getSelectedValue();
            Stock s = new Stock("", 0, TipoPreco.KG, TipoMovimento.ENTRADA);

            Stock antigo = null;
            try {
                antigo = (Stock) s.clone();
            } catch (CloneNotSupportedException ex) {
                JOptionPane.showMessageDialog(null, "ERRO");
            }
            DadosEntrada dialog = new DadosEntrada(this, p, s);
            dialog.setVisible(true);
            if (dialog.isAceite()) {
                p.adicionarMovimento(s);
                actualizarListaProd();

            }
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }


    }//GEN-LAST:event_btnEntradaStockActionPerformed

    private void btnSaidaStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaStockActionPerformed
        try {
            Produto p = (Produto) ListaProdutos.getSelectedValue();
            Stock s = new Stock("", 0, TipoPreco.KG, TipoMovimento.SAIDA);

            Stock antigo = null;
            try {
                antigo = (Stock) s.clone();
            } catch (CloneNotSupportedException ex) {
                JOptionPane.showMessageDialog(null, "ERRO");
            }
            DadosSaida dialog = new DadosSaida(this, p, s);
            dialog.setVisible(true);
            if (dialog.isAceite()) {
                p.adicionarMovimento(s);
                actualizarListaProd();

            }
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }

    }//GEN-LAST:event_btnSaidaStockActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            Produto p = (Produto) ListaProdutos.getSelectedValue();
            Consulta dialog = new Consulta(this, p);
            dialog.setVisible(true);

        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            Produto p = (Produto) ListaProdutos.getSelectedValue();
            DadosProduto dialog = new DadosProduto(this, p);
            dialog.setVisible(true);

            actualizarListaProd();

        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        try {
            Produto p = (Produto) ListaProdutos.getSelectedValue();
            if (JOptionPane.showConfirmDialog(this, "Tem a certeza que quer apagar o produto\n" + p.toString() + "?") == JOptionPane.YES_OPTION) {
                GestaoGumbo.getGumbo().removerProd(p);
                actualizarListaProd();
            }
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void ListaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaProdutosMouseClicked
        if (evt.getClickCount() >= 2) {
            Produto p = (Produto) ListaProdutos.getSelectedValue();
            DadosProduto dialog = new DadosProduto(this, p);
            dialog.setVisible(true);
            actualizarListaProd();
        }
    }//GEN-LAST:event_ListaProdutosMouseClicked


    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased

        searchFilter(searchTxt.getText());
    }//GEN-LAST:event_searchTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gumbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gumbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gumbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gumbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gumbo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaProdutos;
    private javax.swing.JToggleButton btnAdicionar;
    private javax.swing.JToggleButton btnConsultar;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnEntradaStock;
    private javax.swing.JToggleButton btnQuebraStock;
    private javax.swing.JToggleButton btnRemover;
    private javax.swing.JToggleButton btnSaidaStock;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables

    private void actualizarListaProd() {
        modeloListaProdutos = new DefaultListModel();
        for (Produto p : GestaoGumbo.getGumbo().getProd()) {
            modeloListaProdutos.addElement(p);
        }
        
        ListaProdutos.setModel(modeloListaProdutos);
    }

    private void searchFilter(String searchTerm) {
        DefaultListModel filteredItems = new DefaultListModel();
        ArrayList prods = GestaoGumbo.getGumbo().getProd();

        prods.stream().forEach((prod) -> {
            String prodName = prod.toString().toLowerCase();
            if (prodName.contains(searchTerm.toLowerCase())) {
                filteredItems.addElement(prod);
            }

        });

        ListaProdutos.setModel(filteredItems);

    }

}
